version: '3.8'
services:
  postgres:
    image: adonaisoft/labpostgres
    restart: always
    container_name: banco
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_PASSWORD: 1816
    ports:
      - "5440:5432"
    volumes:
      - ./docker:/var/lib/postgresql/data
    networks:
      - utfpr-network
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      TZ: America/Sao_Paulo
      PGADMIN_DEFAULT_EMAIL: geovane@adonaisoft.com.br
      PGADMIN_DEFAULT_PASSWORD: 1816
    networks:
      - utfpr-network
    ports:
      - "8081:80"
    depends_on:
      - postgres
networks:
  utfpr-network:
    driver: bridge